### PR TITLE
Milestone 1 Completion

### PR DESCRIPTION
**Pull request by ershadul1**
### What does this PR do?

- [X] Creates a react app
- [X] Adds linters (eslint and stylelint)
- [X] Adds npm packages (big.js, prop-types, etc.)

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Well done. I can say the project was well setup. The necessary packages have been installed and the app can be started by running `npm start`. That's good.
Let's however fix one thing before merging this PR.
- [ ] make your README more descriptive. Use [this](https://microverse-tse.slack.com/archives/DNE0RG96J/p1579571252000300) template


### Martin Afani

**Comment by ershadul1** [comment]
- [X] Updated README.md

**Review by mosaaleb — CHANGES_REQUESTED** [review]
#### Changes required

Well done @ershadul1 :clap:. Thanks for implementing the changes from the previous review. However, we still need to deploy the app on Heroku and the live link is included at the README.md file.



Please make sure to handle this requirement and submit a new code review.

##### Muhammad Ebeid

**Comment by ershadul1** [comment]
- [X] Deployed the app on Heroku
- [X] Added live link in README.md

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Well done @ershadul1! Nice job working on the suggested changes! :+1: Please add the `.eslintcache` file to your `.gitignore` file before merging your PR since it is irrelevant to your project.

_Happy coding!_ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
